const circuitos = [
  { id: 1, nomeCircuito: 'Luigi Circuit', nomeCopa: 'Mushroom Cup', idCopa: 1 },
  { id: 2, nomeCircuito: 'Moo Moo Meadows', nomeCopa: 'Mushroom Cup', idCopa: 1 },
  { id: 3, nomeCircuito: 'Mushroom Gorge', nomeCopa: 'Mushroom Cup', idCopa: 1 },
  { id: 4, nomeCircuito: 'Toad\'s Factory', nomeCopa: 'Mushroom Cup', idCopa: 1 },
  { id: 5, nomeCircuito: 'Mario Circuit', nomeCopa: 'Flower Cup', idCopa: 2 },
  { id: 6, nomeCircuito: 'Coconut Mall', nomeCopa: 'Flower Cup', idCopa: 2 },
  { id: 7, nomeCircuito: 'Dk Summit', nomeCopa: 'Flower Cup', idCopa: 2 },
  { id: 8, nomeCircuito: 'Wario\'s Gold Mine', nomeCopa: 'Flower Cup', idCopa: 2 },
  { id: 9, nomeCircuito: 'Daisy Circuit', nomeCopa: 'Star Cup', idCopa: 3 },
  { id: 10, nomeCircuito: 'Koopa Cape', nomeCopa: 'Star Cup', idCopa: 3 },
  { id: 11, nomeCircuito: 'Maple Treeway', nomeCopa: 'Star Cup', idCopa: 3 },
  { id: 12, nomeCircuito: 'Grumble Volcano', nomeCopa: 'Star Cup', idCopa: 3 },
  { id: 13, nomeCircuito: 'Dry Dry Ruins', nomeCopa: 'Special Cup', idCopa: 4 },
  { id: 14, nomeCircuito: 'Moonview Highway', nomeCopa: 'Special Cup', idCopa: 4 },
  { id: 15, nomeCircuito: 'Bowser\'s Castle', nomeCopa: 'Special Cup', idCopa: 4 },
  { id: 16, nomeCircuito: 'Rainbow Road', nomeCopa: 'Special Cup', idCopa: 4 },
  { id: 17, nomeCircuito: 'Peach Beach', nomeCopa: 'Shell Cup', idCopa: 5 },
  { id: 18, nomeCircuito: 'Yoshi\'s Fall', nomeCopa: 'Shell Cup', idCopa: 5 },
  { id: 19, nomeCircuito: 'Ghost Valley 2', nomeCopa: 'Shell Cup', idCopa: 5 },
  { id: 20, nomeCircuito: 'Mario Raceway', nomeCopa: 'Shell Cup', idCopa: 5 },
  { id: 21, nomeCircuito: 'Sherbet Land', nomeCopa: 'Banana Cup', idCopa: 6 },
  { id: 22, nomeCircuito: 'Shy Guy Beach', nomeCopa: 'Banana Cup', idCopa: 6 },
  { id: 23, nomeCircuito: 'Delfino Square', nomeCopa: 'Banana Cup', idCopa: 6 },
  { id: 24, nomeCircuito: 'Waluigi Stadium', nomeCopa: 'Banana Cup', idCopa: 6 },
  { id: 25, nomeCircuito: 'Desert Hills', nomeCopa: 'Leaf Cup', idCopa: 7 },
  { id: 26, nomeCircuito: 'Bowser Castle 3', nomeCopa: 'Leaf Cup', idCopa: 7 },
  { id: 27, nomeCircuito: 'DK\'s Jungle Parkway', nomeCopa: 'Leaf Cup', idCopa: 7 },
  { id: 28, nomeCircuito: 'Mario Circuit', nomeCopa: 'Leaf Cup', idCopa: 7 },
  { id: 29, nomeCircuito: 'Mario Circuit 3', nomeCopa: 'Lightning Cup', idCopa: 8 },
  { id: 30, nomeCircuito: 'Peach Gardens', nomeCopa: 'Lightning Cup', idCopa: 8 },
  { id: 31, nomeCircuito: 'DK Mountain', nomeCopa: 'Lightning Cup', idCopa: 8 },
  { id: 32, nomeCircuito: 'Bowser\'s Castle 64', nomeCopa: 'Lightning Cup', idCopa: 8 },
];
